### ISSUE TITLE
invalid memory address

### ISSUE THREAD

**Issue by dirtdiver512** [otoolep/syslog-gollector#18]
Getting the below error while trying to pull stats:

curl 'localhost:8080/statistics?pretty'

2015/02/23 14:15:14 http: panic serving 127.0.0.1:33959: runtime error: invalid memory address or nil pointer dereference
goroutine 15 [running]:
net/http.func·009()
        /usr/lib/go/src/pkg/net/http/server.go:1093 +0xae
runtime.panic(0x6b1500, 0xa25168)
        /usr/lib/go/src/pkg/runtime/panic.c:248 +0x106
github.com/otoolep/syslog-gollector/input.(*Rfc5424Parser).GetStatistics(0x0, 0x711f40, 0x6, 0x7fb7b4071da8, 0x0)
        /home/admin-ti/syslog-gollector/src/github.com/otoolep/syslog-gollector/input/parser.go:49 +0x5
main.ServeStatistics(0x7fb7b4071cf8, 0xc21000fb40, 0xc210072820)
        /home/admin-ti/syslog-gollector/src/github.com/otoolep/syslog-gollector/syslog-gollector.go:84 +0x1bc
net/http.HandlerFunc.ServeHTTP(0x7a3328, 0x7fb7b4071cf8, 0xc21000fb40, 0xc210072820)
        /usr/lib/go/src/pkg/net/http/server.go:1220 +0x40
net/http.(*ServeMux).ServeHTTP(0xc21001e8d0, 0x7fb7b4071cf8, 0xc21000fb40, 0xc210072820)
        /usr/lib/go/src/pkg/net/http/server.go:1496 +0x163
net/http.serverHandler.ServeHTTP(0xc21001f5a0, 0x7fb7b4071cf8, 0xc21000fb40, 0xc210072820)
        /usr/lib/go/src/pkg/net/http/server.go:1597 +0x16e
net/http.(*conn).serve(0xc21006a480)
        /usr/lib/go/src/pkg/net/http/server.go:1167 +0x7b7
created by net/http.(*Server).Serve
        /usr/lib/go/src/pkg/net/http/server.go:1644 +0x28b

**Comment by otoolep** [comment]
Thanks for the report @dirtdiver512 

I have a feeling this was fixed in a fork by https://github.com/emmanuel/syslog-gollector/commit/d957c153207c8f83859e1985bdd66e383d6ebc90. I'm going to port this change and close this issue. Let me know if you see it again.

**Comment by otoolep** [comment]
Yeah, this is basically hitting the stats endpoint if the `server` or `parser` objects are not allocated. This can happen if Kafka can't be contacted, or if parsing is disabled.

I'll fix this shortly.

**Comment by otoolep** [comment]
Fixed.

**Comment by dirtdiver512** [comment]
Just updated with the lasted and still getting the below…?

 

 

2015/03/02 18:41:09 http: panic serving 127.0.0.1:44873: runtime error: invalid memory address or nil pointer dereference

goroutine 14 [running]:

net/http.func·009()

  /usr/lib/go/src/pkg/net/http/server.go:1093 +0xae

runtime.panic(0x6b1500, 0xa25168)

  /usr/lib/go/src/pkg/runtime/panic.c:248 +0x106

github.com/otoolep/syslog-gollector/input.(*Rfc5424Parser).GetStatistics(0x0, 0x711f40, 0x6, 0x7f396a117d80, 0x0)

  /tmp/gollector/src/github.com/otoolep/syslog-gollector/input/parser.go:49 +0x5

main.ServeStatistics(0x7f396a117cd0, 0xc21000f960, 0xc2100724e0)

  /tmp/gollector/src/github.com/otoolep/syslog-gollector/syslog-gollector.go:84 +0x1bc

net/http.HandlerFunc.ServeHTTP(0x7a3368, 0x7f396a117cd0, 0xc21000f960, 0xc2100724e0)

  /usr/lib/go/src/pkg/net/http/server.go:1220 +0x40

net/http.(*ServeMux).ServeHTTP(0xc21001e8d0, 0x7f396a117cd0, 0xc21000f960, 0xc2100724e0)

  /usr/lib/go/src/pkg/net/http/server.go:1496 +0x163

net/http.serverHandler.ServeHTTP(0xc21001fb90, 0x7f396a117cd0, 0xc21000f960, 0xc2100724e0)

  /usr/lib/go/src/pkg/net/http/server.go:1597 +0x16e

net/http.(*conn).serve(0xc210069480)

  /usr/lib/go/src/pkg/net/http/server.go:1167 +0x7b7

created by net/http.(*Server).Serve

  /usr/lib/go/src/pkg/net/http/server.go:1644 +0x28b

**Comment by otoolep** [comment]
Can you provide more details about your setup? Does the gollector connect to Kafka? Please show me the entire output from the program, and the `curl` command you execute.

**Comment by dirtdiver512** [comment]
Yes I just did anouther fresh install.  I am trying to get it to send logs to kafka, single server, basic install.  I can see syslogs going into kafka for a little while but then stops.  So when I try and check the stats I get this error, but the diag still works.   This is my first go at it.  Here is the command and results:

 

 

admin-ti@kafka:/tmp/kafka/kafka_2.10-0.8.2.0$ curl 'localhost:8080/statistics?pretty'

curl: (52) Empty reply from server

admin-ti@kafka:/tmp/kafka/kafka_2.10-0.8.2.0$

 

 

admin-ti@kafka:/tmp/syslog-gollector$ sudo bin/syslog-gollector -topic="poc-av" -udp="0.0.0.0:514"  -parse="false"

[sudo] password for admin-ti:

[03/03/15 07:49:26] [INFO] syslog server starting on kafka, PID 19005

[03/03/15 07:49:26] [INFO] machine has 4 cores

[03/03/15 07:49:26] [INFO] Admin server: localhost:8080

[03/03/15 07:49:26] [INFO] kafka brokers: localhost:9092

[03/03/15 07:49:26] [INFO] kafka topic: poc-av

[03/03/15 07:49:26] [INFO] kafka batch size: 10

[03/03/15 07:49:26] [INFO] kafka buffer time: 1000ms

[03/03/15 07:49:26] [INFO] kafka buffer bytes: 524288

[03/03/15 07:49:26] [INFO] parsing enabled: false

[03/03/15 07:49:26] [INFO] channel buffering capacity: 0

[03/03/15 07:49:26] [INFO] listening on localhost:514 for TCP connections

[03/03/15 07:49:26] [INFO] listening on 0.0.0.0:514 for UDP packets

[03/03/15 07:49:26] [INFO] Admin server started

[03/03/15 07:49:26] [INFO] attempting to connect to Kafka localhost:9092...

[03/03/15 07:49:26] [INFO] kafka producer created

[03/03/15 07:49:26] [INFO] connected to Kafka at localhost:9092

 

 

 

 

 

2015/03/03 07:50:08 http: panic serving 127.0.0.1:38859: runtime error: invalid memory address or nil pointer dereference

goroutine 15 [running]:

net/http.func·009()

        /usr/lib/go/src/pkg/net/http/server.go:1093 +0xae

runtime.panic(0x6b1500, 0xa25168)

        /usr/lib/go/src/pkg/runtime/panic.c:248 +0x106

github.com/otoolep/syslog-gollector/input.(*Rfc5424Parser).GetStatistics(0x0, 0x711f40, 0x6, 0x7f4c05896da8, 0x0)

        /tmp/syslog-gollector/src/github.com/otoolep/syslog-gollector/input/parser.go:49 +0x5

main.ServeStatistics(0x7f4c05896cf8, 0xc21000faa0, 0xc210072b60)

        /tmp/syslog-gollector/src/github.com/otoolep/syslog-gollector/syslog-gollector.go:84 +0x1bc

net/http.HandlerFunc.ServeHTTP(0x7a3368, 0x7f4c05896cf8, 0xc21000faa0, 0xc210072b60)

        /usr/lib/go/src/pkg/net/http/server.go:1220 +0x40

net/http.(*ServeMux).ServeHTTP(0xc21001e8d0, 0x7f4c05896cf8, 0xc21000faa0, 0xc210072b60)

        /usr/lib/go/src/pkg/net/http/server.go:1496 +0x163

net/http.serverHandler.ServeHTTP(0xc21001fb90, 0x7f4c05896cf8, 0xc21000faa0, 0xc210072b60)

        /usr/lib/go/src/pkg/net/http/server.go:1597 +0x16e

net/http.(*conn).serve(0xc21006a480)

        /usr/lib/go/src/pkg/net/http/server.go:1167 +0x7b7

created by net/http.(*Server).Serve

        /usr/lib/go/src/pkg/net/http/server.go:1644 +0x28b

 

 

admin-ti@kafka:/tmp/kafka/kafka_2.10-0.8.2.0$ curl 'localhost:8080/diagnostics?pretty'

{

    "started": "2015-03-03 07:49:26.383983979 -0900 AKST",

    "uptime": "3m9.818499926s"

}admin-ti@kafka:/tmp/kafka/kafka_2.10-0.8.2.0$ <mailto:%7dadmin-ti@kafka:/tmp/kafka/kafka_2.10-0.8.2.0$>

**Comment by otoolep** [comment]
Is *any* call to the statistics API functional? I mean is it working for you, but it fails later?

**Comment by otoolep** [comment]
Fixed by thttps://github.com/otoolep/syslog-gollector/commit/f2ffb54320fd232c286e5a3d272bc5ffeac1fbf2

Thanks @dirtdiver512 for the bug report. Let me know if the latest code doesn't address the crash.
